site_name: 医学文档
repo_url: https://github.com/shutouyabo/docs
edit_uri: edit/main/docs/
site_url: https://docs.zhihu.blog
site_author: yixuewendang
copyright: 'Copyright &copy; 2026 医学文档'

nav:
  - 首页:
    - index.md
    - 关于: main/about.md
    - 友链: main/friendlink.md
    - 名词解释: main/appendix.md
  - 腹部影像解剖图谱:
    - 目录: fubuyingxiang/index.md
    - 第一章 腹部断面影像解剖:
      - fubuyingxiang/1/index.md
      - 1.1 横轴面: fubuyingxiang/1/1-1.md
      - 1.2 冠状面: fubuyingxiang/1/1-2.md
    - 第二章 各脏器增强影像特点:
      - fubuyingxiang/2/index.md
      - 2.1 各脏器强化值: fubuyingxiang/2/2-1.md
      - 2.2 肝: fubuyingxiang/2/2-2.md
      - 2.3 脾脏: fubuyingxiang/2/2-3.md
      - 2.4 胰腺: fubuyingxiang/2/2-4.md
      - 2.5 消化道: fubuyingxiang/2/2-5.md
      - 2.6 肾脏: fubuyingxiang/2/2-6.md
      - 2.7 膀胱: fubuyingxiang/2/2-7.md
      - 2.8 子宫: fubuyingxiang/2/2-8.md
      - 2.9 前列腺: fubuyingxiang/2/2-9.md
    - 第三章 胆道影像解剖:
      - fubuyingxiang/3/index.md
      - 3.1 检查方法: fubuyingxiang/3/3-1.md
      - 3.2 重建影像: fubuyingxiang/3/3-2.md
    - 第四章 消化道影像解剖:
      - fubuyingxiang/4/index.md
      - 4.1 检查方法: fubuyingxiang/4/4-1.md
      - 4.2 横断面: fubuyingxiang/4/4-2.md
      - 4.3 非轴位影像与仿真内镜: fubuyingxiang/4/4-3.md      
    - 第五章 泌尿系统影像解剖:
      - fubuyingxiang/5/index.md
      - 5.1 检查方法: fubuyingxiang/5/5-1.md
      - 5.2 重建影像: fubuyingxiang/5/5-2.md
    - 第六章 腹部血管结构影像解剖:
      - fubuyingxiang/6/index.md
      - 6.1 检查方法: fubuyingxiang/6/6-1.md
      - 6.2 断面血管影像: fubuyingxiang/6/6-2.md
      - 6.3 CTA和MRA血管解剖: fubuyingxiang/6/6-3.md
  - CT诊断学:
    - 目录: ct/index.md
    - 第一章 总论:
      - 第一节 CT 机的基本构造和原理: ct/1/1-1.md
      - 第二节 CT 的应用和进展: ct/1/1-2.md
      - 第三节 常用的 CT 技术术语: ct/1/1-3.md      
    - 第二章 颅脑:
      - ct/2/index.md
      - 第一节 检查方法: ct/2/2-1.md
      - 第二节 正常解剖和 CT 表现: ct/2/2-2.md
      - 第三节 先天颅脑发育畸形和变异: ct/2/2-3.md
      - 第四节 新生儿及婴幼儿脑疾病: ct/2/2-4.md
      - 第五节 脑积水: ct/2/2-5.md
      - 第六节 脑萎缩: ct/2/2-6.md
      - 第七节 脑缺血、出血和脑血管病变: ct/2/2-7.md
      - 第八节 颅脑外伤及其他损害 : ct/2/2-8.md
      - 第九节 颅内肿瘤和囊肿: ct/2/2-9.md
      - 第十节 颅内感染性和其他炎性疾病: ct/2/2-10.md
      - 第十一节 脑白质病及少见的代谢性疾病: ct/2/2-11.md
    - 第三章 眼和眼眶:
      - ct/3/index.md
      - 第一节 检查方法: ct/3/3-1.md
      - 第二节 正常解剖和 CT 表现: ct/3/3-2.md
      - 第三节 先天性病变: ct/3/3-3.md
      - 第四节 外伤和异物: ct/3/3-4.md
      - 第五节 眼眶内炎性病变: ct/3/3-5.md
      - 第六节 眼及眼眶部肿瘤: ct/3/3-6.md
      - 第七节 眶内血管性病变: ct/3/3-7.md
      - 第八节 眼部其他疾病: ct/3/3-8.md
    - 第四章 耳及歞骨:
      - ct/4/index.md
      - 第一节 检查方法: ct/4/4-1.md
      - 第二节 正常解剖和 CT 表现: ct/4/4-2.md
      - 第三节 先天畸形和变异: ct/4/4-3.md
      - 第四节 外伤: ct/4/4-4.md
      - 第五节 炎症性疾病: ct/4/4-5.md
      - 第六节 肿瘤和肿瘤样病变: ct/4/4-6.md
    - 第五章 鼻和鼻旁窦:
      - ct/5/index.md
      - 第一节 检查方法: ct/5/5-1.md
      - 第二节 正常解剖、变异和 CT 表现: ct/5/5-2.md
      - 第三节 先天性疾病: ct/5/5-3.md
      - 第四节 外伤: ct/5/5-4.md
      - 第五节 炎症和囊肿: ct/5/5-5.md
      - 第六节 肿瘤: ct/5/5-6.md
    - 第六章 咽和喉:
      - ct/6/index.md
      - 第一节 检查方法: ct/6/6-1.md
      - 第二节 正常解剖和 CT 表现: ct/6/6-2.md
      - 第三节 先天性疾病: ct/6/6-3.md
      - 第四节 炎症和良性肥大: ct/6/6-4.md
      - 第五节 肿瘤: ct/6/6-5.md
    - 第七章 口腔颌面部:
      - ct/7/index.md
      - 第一节 检查方法: ct/7/7-1.md
      - 第二节 正常解剖和 CT 表现: ct/7/7-2.md
      - 第三节 领骨疾病: ct/7/7-3.md
      - 第四节 涎腺疾病: ct/7/7-4.md
      - 第五节 颞下颌关节疾病: ct/7/7-5.md
    - 第八章 颈部:
      - ct/8/index.md
      - 第一节 检查方法: ct/8/8-1.md
      - 第二节 正常解剖和 CT 表现: ct/8/8-2.md
      - 第三节 先天性囊性病变: ct/8/8-3.md
      - 第四节 颈动脉间隙及其他颈外侧区病变: ct/8/8-4.md
      - 第五节 甲状腺疾病: ct/8/8-5.md
      - 第六节 甲状旁腺疾病: ct/8/8-6.md
    - 第九章 呼吸系统:
      - ct/9/index.md
      - 第一节 检查方法: ct/9/9-1.md
      - 第二节 正常解剖及 CT 表现: ct/9/9-2.md
      - 第三节 呼吸系统疾病的基本 CT 表现: ct/9/9-3.md
      - 第四节 气管支气管疾病: ct/9/9-4.md
      - 第五节 肺先天性疾病: ct/9/9-5.md
      - 第六节 肺不张: ct/9/9-6.md
      - 第七节 肺气肿: ct/9/9-7.md
      - 第八节 肺水肿: ct/9/9-8.md
      - 第九节 肺栓塞和肺梗死: ct/9/9-9.md
      - 第十节 肺部炎症: ct/9/9-10.md
      - 第十一节 肺脓肿: ct/9/9-11.md
      - 第十二节 肺结核: ct/9/9-12.md
      - 第十三节 肺真菌病: ct/9/9-13.md
      - 第十四节 肺寄生虫病和艾滋病: ct/9/9-14.md
      - 第十五节 肺肿瘤: ct/9/9-15.md
      - 第十六节 胸部损伤性疾病: ct/9/9-16.md
      - 第十七节 尘肺: ct/9/9-17.md
      - 第十八节 肺结缔组织疾病: ct/9/9-18.md
      - 第十九节 肺部弥漫性病变: ct/9/9-19.md
      - 第二十节 胸膜、胸壁和横膈疾病: ct/9/9-20.md
      - 第二十一节 乳腺疾病: ct/9/9-21.md
      - 第二十二节 纵隔疾病: ct/9/9-22.md      
    - 第十章 心脏和大血管:
      - ct/10/index.md
      - 第一节 检查方法: ct/10/10-1.md
      - 第二节 正常解剖和 CT 表现: ct/10/10-2.md
      - 第三节 胸部大血管的先天异常: ct/10/10-3.md
      - 第四节 大血管病变: ct/10/10-4.md
      - 第五节 心脏病变: ct/10/10-5.md
      - 第六节 心包病变: ct/10/10-6.md
      - 第七节 心脏及胸部大血管损伤: ct/10/10-7.md      
    - 第十一章 肝脏:
      - ct/11/index.md
      - 第一节 检查方法: ct/11/11-1.md
      - 第二节 正常解剖、变异和血管畸形: ct/11/11-2.md
      - 第三节 原发性肝细胞癌: ct/11/11-3.md
      - 第四节 非肝细胞性肝脏恶性肿瘤及转移瘤: ct/11/11-4.md
      - 第五节 肝血管瘤和其他良性占位性病变: ct/11/11-5.md
      - 第六节 肝脏炎性疾病和寄生虫病: ct/11/11-6.md
      - 第七节 肝脏弥漫性病变及血管病变: ct/11/11-7.md
    - 第十二章 胆道系统:
      - ct/12/index.md
      - 第一节 检查方法: ct/12/12-1.md
      - 第二节 正常解剖、变异和先天异常: ct/12/12-2.md
      - 第三节 胆系结石、炎症和出血: ct/12/12-3.md
      - 第四节 胆囊息肉样病变: ct/12/12-4.md
      - 第五节 胆系恶性肿瘤及肝外胆管梗阻: ct/12/12-5.md
    - 第十三章 胰腺:
      - ct/13/index.md
      - 第一节 检查方法: ct/13/13-1.md
      - 第二节 正常解剖、CT 表现和变异: ct/13/13-2.md
      - 第三节 胰腺炎症: ct/13/13-3.md
      - 第四节 胰腺肿瘤: ct/13/13-4.md
    - 第十四章 脾:
      - ct/14/index.md
      - 第一节 检查方法: ct/14/14-1.md
      - 第二节 正常解剖、先天变异和畸形: ct/14/14-2.md
      - 第三节 脾脏感染及梗死: ct/14/14-3.md
      - 第四节 脾囊肿及肿瘤: ct/14/14-4.md
    - 第十五章 肾、输尿管和膀胱:
      - ct/15/index.md
      - 第一节 检查方法: ct/15/15-1.md
      - 第二节 正常解剖和变异: ct/15/15-2.md
      - 第三节 泌尿系统先天性发育异常: ct/15/15-3.md
      - 第四节 泌尿系结石和积水: ct/15/15-4.md
      - 第五节 泌尿系感染性疾病: ct/15/15-5.md
      - 第六节 肾脏囊性病变: ct/15/15-6.md
      - 第七节 肾、输尿管和膀胱肿瘤: ct/15/15-7.md
      - 第八节 肾血管病变及肾移植: ct/15/15-8.md      
    - 第十六章 肾上腺:
      - ct/16/index.md
      - 第一节 检查方法: ct/16/16-1.md
      - 第二节 正常解剖和 CT 表现: ct/16/16-2.md
      - 第三节 肾上腺增生和肿瘤: ct/16/16-3.md
      - 第四节 肾上腺囊肿、血肿及皮质功能减退: ct/16/16-4.md      
    - 第十七章 胃肠道 :
      - ct/17/index.md
      - 第一节 检查方法: ct/17/17-1.md
      - 第二节 正常解剖和 CT 表现: ct/17/17-2.md
      - 第三节 食管疾病: ct/17/17-3.md
      - 第四节 胃疾病: ct/17/17-4.md
      - 第五节 十二指肠疾病: ct/17/17-5.md
      - 第六节 小肠疾病: ct/17/17-6.md
      - 第七节 大肠疾病: ct/17/17-7.md
      - 第八节 阑尾疾病: ct/17/17-8.md
      - 第九节 肠梗阻: ct/17/17-9.md
    - 第十八章 腹膜腔与腹壁:
      - ct/18/index.md
      - 第一节 检查方法: ct/18/18-1.md
      - 第二节 正常解剖: ct/18/18-2.md
      - 第三节 腹腔积液、脓肿、炎症和网膜缺血: ct/18/18-3.md
      - 第四节 腹膜腔肿瘤: ct/18/18-4.md
      - 第五节 腹壁疾病: ct/18/18-5.md
    - 第十九章 腹膜后腔:
      - ct/19/index.md
      - 第一节 检查方法: ct/19/19-1.md
      - 第二节 正常解剖及变异: ct/19/19-2.md
      - 第三节 腹部大血管疾病: ct/19/19-3.md
      - 第四节 腹膜后腔炎症及脓肿: ct/19/19-4.md
      - 第五节 腹膜后腔肿瘤: ct/19/19-5.md
      - 第六节 腹膜后淋巴结病变: ct/19/19-6.md
      - 第七节 腹膜后纤维化及腰肌病变: ct/19/19-7.md
    - 第二十章 腹部钝伤:
      - ct/20/index.md
      - 第一节 检查方法: ct/20/20-1.md
      - 第二节 腹腔积血: ct/20/20-2.md
      - 第三节 实质性脏器损伤: ct/20/20-3.md
      - 第四节 空腔性脏器损伤: ct/20/20-4.md
    - 第二十一章 盆腔:
      - ct/21/index.md
      - 第一节 检查方法: ct/21/21-1.md
      - 第二节 正常解剖和 CT 表现: ct/21/21-2.md
      - 第三节 前列腺、精囊及睾丸病变: ct/21/21-3.md
      - 第四节 子宫病变: ct/21/21-4.md
      - 第五节 卵巢病变: ct/21/21-5.md
      - 第六节 输卵管病变: ct/21/21-6.md
      - 第七节 盆腔其他病变: ct/21/21-7.md
    - 第二十二章 骨关节及软组织:
      - ct/22/index.md
      - 第一节 概述: ct/22/22-1.md
      - 第二节 正常解剖和 CT 表现: ct/22/22-2.md
      - 第三节 骨与关节创伤: ct/22/22-3.md
      - 第四节 骨关节感染: ct/22/22-4.md
      - 第五节 骨肿瘤及肿瘤样病变: ct/22/22-5.md
      - 第六节 软组织病变: ct/22/22-6.md
      - 第七节 关节疾病: ct/22/22-7.md
      - 第八节 骨缺血性坏死: ct/22/22-8.md
    - 第二十三章 脊柱和脊髓:
      - ct/23/index.md
      - 第一节 检查方法: ct/23/23-1.md
      - 第二节 正常解剖和 CT 表现: ct/23/23-2.md
      - 第三节 脊柱与脊髓的先天性异常: ct/23/23-3.md
      - 第四节 脊柱退行性病变: ct/23/23-4.md
      - 第五节 椎管内结构损伤: ct/23/23-5.md
      - 第六节 椎间盘及椎管内感染性疾病: ct/23/23-6.md
      - 第七节 椎管内血管疾病: ct/23/23-7.md
      - 第八节 椎管内肿瘤: ct/23/23-8.md
    - 附录 A 参考文献:
      - ct/24/index.md
  - ICU主治医生手册:
    - 目录: icu/index.md
    - 第一章 多器官功能障碍综合征和多器官功能衰竭:
      - icu/1/index.md
      - 一、前沿学术综述: icu/1/1-1.md
      - 二、临床问题: icu/1/1-2.md
    - 第二章 休克与循环功能支持:
      - icu/2/index.md
      - 一、前沿学术综述: icu/2/2-1.md
      - 二、临床问题: icu/2/2-2.md
    - 第三章 超声在休克和循环功能监测及支持中的应用:
      - icu/3/index.md
      - 一、前沿学术综述: icu/3/3-1.md
      - 二、临床问题: icu//3-2.md
    - 第四章 血流动力学和氧代谢监测:
      - icu/4/index.md
      - 一、前沿学术综述: icu/4/4-1.md
      - 二、临床问题: icu/4/4-2.md
    - 第五章 急性呼吸衰竭与急性呼吸窘迫综合征:
      - icu/5/index.md
      - 一、前沿学术综述: icu/5/5-1.md
      - 二、临床问题: icu/5/5-2.md
    - 第六章 急性加重期慢性阻塞性肺疾病:
      - icu/6/index.md
      - 一、前沿学术综述: icu/6/6-1.md
      - 二、临床问题: icu/6/6-2.md
    - 第七章 重症支气管哮喘急性发作:
      - icu/7/index.md
      - 一、前沿学术综述: icu/7/7-1.md
      - 二、临床问题: icu/7/7-2.md
    - 第八章 医院获得性肺炎和呼吸机相关性肺炎:
      - icu/8/index.md
      - 一、前沿学术综述: icu/8/8-1.md
      - 二、临床问题: icu/8/8-2.md
    - 第九章 氧疗与人工气道管理:
      - icu/9/index.md
      - 一、前沿学术综述: icu/9/9-1.md
      - 二、临床问题: icu/9/9-2.md
    - 第十章 机械通气与撤机:
      - icu/10/index.md
      - 一、前沿学术综述: icu/10/10-1.md
      - 二、临床问题: icu/10/10-2.md
    - 第十一章 急性肾衰竭:
      - icu/11/index.md
      - 一、前沿学术综述: icu/11/11-1.md
      - 二、临床问题: icu/11/11-2.md
    - 第十二章 血液净化与肾脏替代治疗:
      - icu/12/index.md
      - 一、前沿学术综述: icu/12/12-1.md
      - 二、临床问题: icu/12/12-2.md
    - 第十三章 急性肝衰竭:
      - icu/13/index.md
      - 一、前沿学术综述: icu/13/13-1.md
      - 二、临床问题: icu/13/13-2.md
    - 第十四章 肝移植围手术期管理:
      - icu/14/index.md
      - 一、前沿学术综述: icu/14/14-1.md
      - 二、临床问题: icu/14/14-2.md
    - 第十五章 重症急性胰腺炎:
      - icu/15/index.md
      - 一、前沿学术综述: icu/15/15-1.md
      - 二、临床问题: icu/15/15-2.md
    - 第十六章 血栓性疾病:
      - icu/16/index.md
      - 一、前沿学术综述: icu/16/16-1.md
      - 二、临床问题: icu/16/16-2.md
    - 第十七章 心肺脑复苏:
      - icu/17/index.md
      - 一、前沿学术综述: icu/17/17-1.md
      - 二、临床问题: icu/17/17-2.md
    - 第十八章 多发性创伤:
      - icu/18/index.md
      - 一、前沿学术综述: icu/18/18-1.md
      - 二、临床问题: icu/18/18-2.md
    - 第十九章 水电解质紊乱:
      - icu/19/index.md
      - 一、前沿学术综述: icu/19/2-1.md
      - 二、临床问题: icu/19/2-2.md
    - 第二十章 酸碱平衡紊乱:
      - icu/20/index.md
      - 一、前沿学术综述: icu/20/20-1.md
      - 二、临床问题: icu/20/20-2.md
    - 第二十一章 重症患者的镇痛镇静:
      - icu/21/index.md
      - 一、前沿学术综述: icu/21/21-1.md
      - 二、临床问题: icu/21/21-2.md
    - 第二十二章 重症患者的营养支持:
      - icu/22/index.md
      - 一、前沿学术综述: icu/22/22-1.md
      - 二、临床问题: icu/22/22-2.md
    - 第二十二章 重症患者的营养支持:
      - icu/23/index.md
      - 一、前沿学术综述: icu/23/23-1.md
      - 二、临床问题: icu/23/23-2.md
    - 第二十四章 体外膜氧合:
      - icu/24/index.md
      - 一、前沿学术综述: icu/24/24-1.md
      - 二、临床问题: icu/24/24-2.md
    - 第二十五章 重症医学科获得性感染与感染控制:
      - icu/25/index.md
      - 一、前沿学术综述: icu/25/25-1.md
      - 二、临床问题: icu/25/25-2.md
    - 附录 A 中国重症加强治疗病房（ICU）建设与管理指南（2006）:
      - icu/26/index.md
      - 一、 引 言: icu/26/26-1.md
      - 二、基本要求: icu/26/26-2.md
      - 三、ICU 的规模: icu/26/26-3.md
      - 四、ICU 的人员配备: icu/26/26-4.md
      - 五、ICU 医护人员专业要求: icu/26/26-5.md
      - 六、ICU 的医疗管理: icu/26/26-6.md
      - 七、ICU 病房建设标准: icu/26/26-7.md
      - 八、ICU 必配设备: icu/26/26-8.md
      - 九、ICU 选配设备: icu/26/26-9.md
    - 附录 B 成人严重感染与感染性休克血流动力学监测与支持指南（2006）:
      - icu/27/index.md
      - 一、 引 言: icu/27/27-1.md
      - 二、 严重感染与感染性休克的血流动力学特点: icu/27/27-2.md
      - 三、 严重感染与感染性休克的诊断: icu/27/27-3.md
      - 四、严重感染与感染性休克血流动力学监测的目的与意义: icu/27/27-4.md
      - 五、 常用监测指标的选择与影响因素: icu/27/27-5.md
      - 六、 功能性血流动力学监测: icu/27/27-6.md
      - 七、 成人严重感染与感染性休克的血流动力学支持: icu/27/27-7.md
      - 八、 成人严重感染与感染性休克的集束化治疗: icu/27/27-8.md
    - 附录 C 急性肺损伤／急性呼吸窘迫综合征诊断和治疗指南（2006）:
      - icu/28/index.md
      - 一、 引 言: icu/28/28-1.md
      - 二、ALI／ARDS 的概念与流行病学: icu/28/28-2.md
      - 三、ALI／ARDS 病理生理与发病机制: icu/28/28-3.md
      - 四、ALI／ARDS 的临床特征与诊断: icu/28/28-4.md
      - 五、ALI／ARDS 的治疗: icu/28/28-5.md
    - 附录 D 机械通气临床应用指南（2006）:
      - icu/29/index.md
      - 一、 引 言: icu/29/29-1.md
      - 二、 危重症患者人工气道的选择: icu/29/29-2.md
      - 三、人工气道的管理: icu/29/29-3.md
      - 四、机械通气的目的和应用指征: icu/29/29-4.md
      - 五、无创正压通气（NPPV）: icu/29/29-5.md
      - 六、 机械通气的基本模式: icu/29/29-6.md
      - 七、 氧合监护: icu/29/29-7.md
      - 八、机械通气的并发症: icu/29/29-8.md
      - 九、呼吸机撤离: icu/29/29-9.md
    - 附录 E 2012 重症成人患者疼痛、烦躁和谵妄处理临床实践指南:
      - icu/30/index.md
      - 一、证据质量和建议力度: icu/30/30-1.md
      - 二、指 南: icu/30/30-2.md
    - 附录 F 2012 成人严重感染和感染性休克治疗指南:
      - icu/31/index.md
    - 附录 G KIDGO 急性肾损伤诊疗指南:
      - icu/32/index.md
    - 附录 H 重症医学科常用静脉药物应用指南:
      - icu/33/index.md    
  - X线读片指南:
    - 目录: x/index.md
    - 第一章 腹部断面影像解剖:
      - x/index.md
      - 1.1 横轴面: x/1/1-1.md
      - 1.2 冠状面: x/1/1-2.md
    - 第二章 各脏器增强影像特点:
      - x/2/index.md
      - 2.1 各脏器强化值: x/2/2-1.md
      - 2.2 肝: x/2/2-2.md
  - 病理学:
    - 目录: binglixue/index.md
    - 第一章 腹部断面影像解剖:
      - binglixue/index.md
      - 1.1 横轴面: binglixue/1/1-1.md
      - 1.2 冠状面: binglixue/1/1-2.md
    - 第二章 各脏器增强影像特点:
      - binglixue/2/index.md
      - 2.1 各脏器强化值: binglixue/2/2-1.md
      - 2.2 肝: binglixue/2/2-2.md
  - 急诊内科学:
    - 目录: jizhenneikexue/index.md
    - 第一章 腹部断面影像解剖:
      - jizhenneikexue/index.md
      - 1.1 横轴面: jizhenneikexue/1/1-1.md
      - 1.2 冠状面: jizhenneikexue/1/1-2.md
    - 第二章 各脏器增强影像特点:
      - jizhenneikexue/2/index.md
      - 2.1 各脏器强化值: jizhenneikexue/2/2-1.md
      - 2.2 肝: jizhenneikexue/2/2-2.md
  - 精神病学:
    - 目录: jingshenbingxue/index.md
    - 第一章 腹部断面影像解剖:
      - jingshenbingxue/index.md
      - 1.1 横轴面: jingshenbingxue/1/1-1.md
      - 1.2 冠状面: jingshenbingxue/1/1-2.md
    - 第二章 各脏器增强影像特点:
      - jingshenbingxue/2/index.md
      - 2.1 各脏器强化值: jingshenbingxue/2/2-1.md
      - 2.2 肝: jingshenbingxue/2/2-2.md
  - 临床心电图详解与诊断:
    - 目录: linchuangxindiantu/index.md
    - 第一章 腹部断面影像解剖:
      - linchuangxindiantu/index.md
      - 1.1 横轴面: linchuangxindiantu/1/1-1.md
      - 1.2 冠状面: linchuangxindiantu/1/1-2.md
    - 第二章 各脏器增强影像特点:
      - linchuangxindiantu/2/index.md
      - 2.1 各脏器强化值: linchuangxindiantu/2/2-1.md
      - 2.2 肝: linchuangxindiantu/2/2-2.md
  - 免疫学:
    - 目录: mianyixue/index.md
    - 第一章 腹部断面影像解剖:
      - mianyixue/index.md
      - 1.1 横轴面: mianyixue/1/1-1.md
      - 1.2 冠状面: mianyixue/1/1-2.md
    - 第二章 各脏器增强影像特点:
      - mianyixue/2/index.md
      - 2.1 各脏器强化值: mianyixue/2/2-1.md
      - 2.2 肝: mianyixue/2/2-2.md
  - 内科疾病鉴别诊断学:
    - 目录: neikejibing/index.md
    - 第一章 腹部断面影像解剖:
      - neikejibing/index.md
      - 1.1 横轴面: neikejibing/1/1-1.md
      - 1.2 冠状面: neikejibing/1/1-2.md
    - 第二章 各脏器增强影像特点:
      - neikejibing/2/index.md
      - 2.1 各脏器强化值: neikejibing/2/2-1.md
      - 2.2 肝: neikejibing/2/2-2.md

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.footer
    - navigation.top
    - toc.follow
    - announce.dismiss
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: false

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized
  - add-number:
      strict_mode: False
      order: 2
  - git-authors:
      show_contribution: true
  - redirects:
      redirect_maps:
        cases.md: https://database.feiyue.online
