site_name: 医学文档
repo_url: https://github.com/THU-feiyue/THU-feiyue
edit_uri: edit/main/docs/
site_url: https://docs.zhihu.blog
site_author: THU Feiyue Team
copyright: 'Copyright &copy; 2024 THU Feiyue Team'

nav:
  - 首页:
    - index.md
    - 关于: main/about.md
    - 友链: main/friendlink.md
    - 名词解释: main/appendix.md
  - 腹部影像解剖图谱:
    - 目录: fubuyingxiang/index.md
    - 第一章 腹部断面影像解剖:
      - fubuyingxiang/1/index.md
      - 1.1 横轴面: fubuyingxiang/1/1-1.md
      - 1.2 冠状面: fubuyingxiang/1/1-2.md
    - 第二章 各脏器增强影像特点:
      - fubuyingxiang/2/index.md
      - 2.1 各脏器强化值: fubuyingxiang/2/2-1.md
      - 2.2 肝: fubuyingxiang/2/2-2.md
      - 2.3 脾脏: fubuyingxiang/2/2-3.md
      - 2.4 胰腺: fubuyingxiang/2/2-4.md
      - 2.5 消化道: fubuyingxiang/2/2-5.md
      - 2.6 肾脏: fubuyingxiang/2/2-6.md
      - 2.7 膀胱: fubuyingxiang/2/2-7.md
      - 2.8 子宫: fubuyingxiang/2/2-8.md
      - 2.9 前列腺: fubuyingxiang/2/2-9.md
    - 第三章 胆道影像解剖:
      - fubuyingxiang/3/index.md
      - 3.1 检查方法: fubuyingxiang/3/3-1.md
      - 3.2 重建影像: fubuyingxiang/3/3-2.md
    - 第四章 消化道影像解剖:
      - fubuyingxiang/4/index.md
      - 4.1 检查方法: fubuyingxiang/4/4-1.md
      - 4.2 横断面: fubuyingxiang/4/4-2.md
      - 4.3 非轴位影像与仿真内镜: fubuyingxiang/4/4-3.md      
    - 第五章 泌尿系统影像解剖:
      - fubuyingxiang/5/index.md
      - 5.1 检查方法: fubuyingxiang/5/5-1.md
      - 5.2 重建影像: fubuyingxiang/5/5-2.md
    - 第六章 腹部血管结构影像解剖:
      - fubuyingxiang/6/index.md
      - 6.1 检查方法: fubuyingxiang/6/6-1.md
      - 6.2 断面血管影像: fubuyingxiang/6/6-2.md
      - 6.3 CTA和MRA血管解剖: fubuyingxiang/6/6-3.md
  - 录取及之后:
    - 录取及之后: afterad/index.md
    - Funding: afterad/funding.md
    - 等待 Offer: afterad/waiting.md
    - 比较决定: afterad/compare.md
    - 签证: afterad/visa.md
    - 前往: afterad/travel.md
    - 租房: afterad/rent.md
  - 案例: cases.md
  - 文章阅读: reading/index.md
  - 联系与支持:
    - 联系与支持: contact/support.md
    - 功德墙: contact/contributor.md

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.footer
    - navigation.top
    - toc.follow
    - announce.dismiss
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: false

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized
  - add-number:
      strict_mode: False
      order: 2
  - git-authors:
      show_contribution: true
  - redirects:
      redirect_maps:
        cases.md: https://database.feiyue.online
